### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Julien-Kl** [Kelmatou/LeagueAPI#23]
Hello,

I would like to code an app with some friends. We are not really used to swift code, that would be more like an introduction for us. We are facing an installation issue. By following the instruction, carthage bootstrap --platform iOS gives us an error (see sc), so we used carthage update --use-xcframeworks, but still doesn't work. The terminal installation doesn't finish succesfully.

We have the error "Could not find module 'LeagueAPI' for target 'x86_64-apple-ios-simulator'; found: arm64, armv7-apple-ios, arm64-apple-ios, arm, armv7" in xCode and we can't figure where it comes from.

We may miss something obvious here but we are struggling to find a solution for a week now. We'll highly appreciate any help please.

Have a good day.

<img width="570" alt="Capture d’écran 2021-02-26 à 11 26 11" src="https://user-images.githubusercontent.com/79696303/109289773-fcc82e80-7826-11eb-8297-e9bde62a4a96.png">
<img width="564" alt="Capture d’écran 2021-02-26 à 11 26 40" src="https://user-images.githubusercontent.com/79696303/109289780-fe91f200-7826-11eb-958e-a3baef61df4c.png">

**Comment by Kelmatou** [comment]
@Julien-Kl looks like since Xcode 12 you need to run `carthage bootstrap --platform iOS --use-xcframeworks`
Make sure you clean previous Carthage previous builds with `rm -rf Carthage/ Cartfile.resolved`

I just tried with a new iOS project, ran `carthage bootstrap --platform iOS --use-xcframeworks` and added the Carthage/Build/LeagueAPI.xcframework to the embedded libraries and it was working well.

Let me know if you have any issue with this process

**Comment by Julien-Kl** [comment]
Good morning,

It solved my problem perfectly. I will be able to go further. Thank you a lot. I also saw you've already updated instructions. Well done for your work and your reactivity ! 

Have a good day !
